### ISSUE TITLE
Chat communication

### ISSUE THREAD

**Issue by ph1p** [reactjs/de.reactjs.org#32]
Hi!

I've created a slack chat to communicate.

You can join with this link:....

Or should we use something like discord or gitter?

Update:

We use official Slack and joining the #de channel

**Comment by JohannesKlauss** [comment]
I am happy with slack.

**Comment by markus-willems** [comment]
If you go to https://isreacttranslatedyet.com/ and scroll to the bottom it says:

> We also have a [Slack channel](https://rt-slack-invite.herokuapp.com/)!

Isn't this the official Slack channel? I already created a channel (#de) yesterday :)

**Comment by ph1p** [comment]
@markus-willems Oh cool! Let's use that!

**Comment by ChrisB9** [comment]
i have added it to the readme, so that it is available for everyone quickly
