### ISSUE TITLE
Set up DocSearch

### ISSUE THREAD

**Issue by tesseralis** [reactjs/de.reactjs.org#80]
Congrats on almost completing the core pages! One of the final steps is to change the [DocSearch API key](https://github.com/reactjs/es.reactjs.org/blob/ed07fa53dc9ab7950e630900f7da3a7c821d63a6/src/components/LayoutHeader/DocSearch.js#L25).

One of the maintainers needs to [sign up for DocSearch](https://community.algolia.com/docsearch/#join-docsearch-program) in order to do this.

**Comment by ph1p** [comment]
I've already added a key https://github.com/reactjs/de.reactjs.org/pull/74

**Comment by ph1p** [comment]
I checked it again and already added a docsearch API key.
